version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: purchases
      MYSQL_USER: user
      MYSQL_PASSWORD: pass_oct_10_2023
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: purchases
      MYSQL_USER: user
      MYSQL_PASSWORD: pass_oct_10_2023
      APP_ENV: production
      REACT_APP_API_HOST: http://localhost:3000
    depends_on:
      - db

volumes:
  db-data:
